version: "3.8"

services:
  olcrtc-bot:
    build: .
    container_name: olcrtc_telegram_bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_PATH: /app/data/database.sqlite
    volumes:
      - ./data:/app/data
